version: "3.8"

services:
    web:
        build: ./app
        container_name: fastapi_app
        restart: always
        env_file:
            - .env
        volumes:
            - ./app:/app
            - ./.env:/app/.env
            - ./uploads:/app/uploads
            - ./app/alembic/versions:/app/alembic/versions
        expose:
            - "8000"
        depends_on:
            - db
        networks:
            - memento_net

    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
        networks:
            - memento_net

    

volumes:
    fastapi-app_pgdata:

networks:
    memento_net:
